name: Swift CI

on: [push, pull_request]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.8", "5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Test Server
        run: |
          make setup_server
          sleep 10
          curl http://localhost:8080
          make teardown_server
      # - name: Build
      #   run: swift build
      # - name: Run tests
      #   run: swift test --skip IntegrationTests
