name: macOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Execute tests on macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode-version: "15.3"   # Swift 5.10
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Setup environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
      - name: Swift version
        run: swift --version
      - name: Run unit tests
        run: make unit_test
      - name: Run integration tests
        run: make integration_test